$(document).ready(function(){
  $('img').fadeIn(3000);
  $('button').click(function(){
    $('img').css({'border-radius':'10em'});
  });
  $('body').click(function(){
    $(this).css({'background':'black'});
    });
});
