$(document).ready(function(){
$('img').fadeIn("slow");
  $('button').click(function(){
    $('img').hide();
  });
  $('#rounded').click(function(){
    $('div').css({'border-radius':'10em'});
});
$('p').click(function(){
  $('custom')css({'background':'yellow']);
                 });
});
