$(document).ready(function(){
  $('div').click(function(){
    $(this).hide(){
});
$('img').click(function(){
  $('img.css({'border-radius':100px'});
});
  });  
  
$(document).ready(function(){
  $('#rounded').click(function(){
    $('div').css({'border-radius':'10em'});
  });
  $('p').click(function(){
    $('#custom').css({'background':'yellow'});
  });
  $('div').click(function(){
    $(this).fadeOut('slow');
  });
});
