$(document).ready(function(){
  $('#rounded').click(function(){  
    $('div').css({'border-radius':'10em'});
  });
  $('p').click(function(){
    $('div').css({'background-color':'pink'});
  });
  $('img').fadeOut();
});
