$(document).ready(function(){
$('#rounded').click(function(){
  $('div').css({'border-radius':'10em'});
 });
$('img').click(function(){
    $('img').hide();
 });
   $('div').click(function(){
    $(this).fadeout(3000);
});
