$(document).ready(function(){
  $('div').click(function(){
    $(this).hide();
  });
  $('img').click(function(){
    $('img').css({'border-radius':'10em'});
  });
  $('button').click(function(){
    $('body').css({'background':'red'});
  });
});
